---

- hosts: all
  gather_facts: false

  # The variables you would most likely want/need to override have been included
  vars:

    # Facts
    client_agent_status_facts_generate: true
    client_agent_status_facts_verbose: true

     # Reports
    client_agent_status_reports_generate: true
    client_agent_status_reports_backup: true
    client_agent_status_reports_host: 192.168.0.124
    client_join_reports: 
      - src:  client_agent_status_report.csv.j2   
        dest: client_agent_status_report.csv
      - src:  client_agent_status_report.html.j2
        dest: client_agent_status_report.html
  roles:
    - name: oneidentity.authentication_services.client_agent_status
