---

- hosts: all
  gather_facts: false

  # The variables you would most likely want/need to override have been included
  vars:

    # Active Directory
    client_domain: itg-internal.com
    client_username: administrator
    client_password: Admin123

    # Report parameters
    unix_enabled_ad_users_base_container: 'CN=Users,DC=itg-internal,DC=com'

    # Reports
    unix_enabled_ad_users_reports_generate: true
    unix_enabled_ad_users_reports_backup: true
    unix_enabled_ad_users_reports_host: 192.168.0.123
    unix_enabled_ad_users_reports:
    - src:  unix_enabled_ad_users_report.csv.j2
      dest: /home/reports/unix_enabled_ad_users_report.csv
    - src:  unix_enabled_ad_users_report.html.j2
      dest: /home/reports/unix_enabled_ad_users_report.html

  roles:
    - name: oneidentity.authentication_services.unix_enabled_ad_users
