---

- hosts: managed_sas_hosts

  # The variables you would most likely want/need to override have been included
  vars:

    # Directories
    client_sw_dir: "client"
    client_sw_tmp_dir: /tmp/1id

    # Software states
    client_sw_pkg_state:
      vasclnt: present
      # vasclnts: check 
      vasgp: present 
      # vasgps: check 
      vassc: present
      # vascert: check
      # dnsupdate: check 
      # pamdefender: present
      # vasyp: check 
      # vasqa: check 
      # vasproxy: check 
      # vasdev: check 

    # Facts
    client_sw_facts_generate: true
    client_sw_facts_verbose: false 
    
    # Reports
    client_sw_reports_generate: true 
    client_sw_reports_backup: true
    client_sw_reports_host: awx-itg
    client_sw_reports: 
      - src:  client_sw_report.csv.j2   
        dest: /home/reports/client_sw_report.csv
      - src:  client_sw_report.html.j2
        dest: /home/reports/client_sw_report.html

  roles:
    - name: oneidentity.authentication_services.client_sw
